---
name: module3_task0

"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  builds:
    name: job1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Validate Makefile
        run: make help
        working-directory: module3_task0
