name: module3_task0

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Validate Makefile
      run: make help
      working-directory: module3_task0

