---
name: module3_task2
"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  builds:
    name: job1
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install markdownlint from npm
        run: npm install -g markdownlint-cli
      - name: Setup Env and Validate Makefile help
        run: |
          make lint
          ./setup.sh
          make help
          make build
          make clean
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
          make package
          make unit-tests
          make validate
          make integration-tests
        working-directory: module3_task2
