---
name: module3_task1

"on":
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Environment
        run: ../scripts/setup.sh  
      - name: Validate Makefile
        run: |
          make help
          make build
          make clean
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
        working-directory: module3_task1
