---
name: module3_task0

on:   # yamllint disable-line rule:truthy
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   # yamllint disable-line
      - uses: actions/checkout@v2
      - name: Validate Makefile
        run: make help
        working-directory: module3_task0
