---
name: module3_task0

"on":
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Env and Validate Makefile
        run: ./setup.sh
        run: make help
        run: make build
        run: make clean
        make POST_NAME=who-are-we POST_TITLE="Who are we" post
        working-directory: module3_task0
