
---
name: module3_task2
"on":
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  builds:
    name: job1
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Install NodeJs
        run: sudo apt install npm
        
      - name: Install markdownlint from npm
        run: npm install markdownlint --save-dev
          
      - name: Setup Env and Validate Makefile help
        run: |
          make lint
          ./setup.sh
          make help
          make build
          make clean
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
          make package
        working-directory: module3_task2
